<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace Model\PommProject\PommSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Comment
 *
 * Structure class for relation "pomm"."comment".
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Comment extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('"pomm"."comment"')
            ->setPrimaryKey([])
            ->addField('id', 'int4')
            ->addField('article_slug', 'varchar')
            ->addField('email', 'varchar')
            ->addField('created_at', 'timestamp')
            ->addField('website', 'varchar')
            ->addField('content', 'text')
            ->addField('name', 'varchar')
            ;
    }
}
