<?php
/**
 * This file has been automaticaly generated by Pomm Cli package.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace Model\PommProject\PommSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * News
 *
 * Structure class for relation pomm.news.
 * The slugs are generated automatically from the title using a trigger.
 *
 * slug:
 * The slugs are generated automatically from the title using a trigger.
 * title:
 * Titles are rendered in a h1 tag.
 * published_at:
 * When null, the news is not published.
 *
 * @see RowStructure
 */
class News extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     * @return null
     */
    public function __construct()
    {
        $this
            ->setRelation('pomm.news')
            ->setPrimaryKey(['slug'])
            ->addField('slug', 'varchar')
            ->addField('title', 'varchar')
            ->addField('created_at', 'timestamp')
            ->addField('published_at', 'timestamp')
            ->addField('content', 'text')
            ;
    }
}
